# This is a basic workflow that is manually triggered
name: Build Packs

# Controls when the action will run. Workflow runs when release is published.
on: 
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called buildPacks
  buildPacks:
    # The type of runner that the job will run on. This must be ubuntu for the zip command to work.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Each step runs a single command using the runners shell.
      # 1. Checkout our repository so we can do things on it.
    - name: Checkout 
      uses: actions/checkout@v4
      # 2. Make sure node is set up. This may be an unecessary step.
    - name: Node Setup 
      uses: actions/setup-node@v3
      with:
        node-version: 18
      # 3. Install the FoundryVTT CLI.
    - run: npm install -g @foundryvtt/foundryvtt-cli 
      # 4. Configure the datapath as the github workspace variable.
    - run: fvtt configure set "dataPath" ${GITHUB_WORKSPACE}
      # 5. Package each folder of source json files into the appropriate LevelDB pack.
    - run: ./packall.sh
      # 6. get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

      # 7. Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/lhrpg-${{github.event.release.tag_name}}.zip
      # 8. Zip up the branch with the LevelDB packs.
    - name: Zip 
      # Exclude the source json files from the final package, as well as any git folders.
      run: zip -r loghorizontrpg-compendium-${{github.event.release.tag_name}}.zip module.json packs/ --exclude="*packs/*/_source*"
    # 9. Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.unpublished }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./loghorizontrpg-compendium-${{github.event.release.tag_name}}.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}